### ISSUE TITLE
library() nicht in .R file

### ISSUE THREAD

**Issue by juliabrosig** [daryabusen/fueri#1]
https://github.com/daryabusen/fueri/blob/master/R/checkHeight.R

Ich glaube library(...) macht man nicht in packages --> http://r-pkgs.had.co.nz/package.html,

library() is not useful when you're developing a package because you have to 
install the package first. In future chapters you'll learn about 
devtools::load_all() and RStudio's "Build and reload", which allows you to skip 
install and load a source package directly into memory:

**Comment by daryabusen** [comment]
erledigt
